services:
  bds:
    image: itzg/minecraft-bedrock-server
    container_name: bds-runtime
    ports:
      - "19133:19133/udp"
    environment:
      EULA: "TRUE"
      
      SERVER_NAME: "Enjoyed!!"
      GAMEMODE: survival
      DIFFICULTY: normal
      ALLOW_CHEATS: "true"
      MAX_PLAYERS: 10

      ONLINE_MODE: "true"
      ALLOW_LIST: "false"

      SERVER_PORT: 19133
      SERVER_PORT_V6: 19134

      LEVEL_NAME: "Bedrock level"

      VIEW_DISTANCE: 32
      TICK_DISTANCE: 4

      PLAYER_IDLE_TIMEOUT: 0
      DEFAULT_PLAYER_PERMISSION_LEVEL: member
      TEXTUREPACK_REQUIRED: "false"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
  backend:
    build: ./backend
    container_name: bds-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      # Mavenの依存関係キャッシュを保持して高速化
      - maven-repo:/root/.m2
    # ホスト側のmvnwを直接叩く設定
    command: ./mvnw spring-boot:run
    working_dir: /app
    depends_on:
      - bds

volumes:
  maven-repo: # 依存ライブラリを保存するためのボリューム